version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "support-portal"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d support-portal"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    networks:
      - app-network

  migrate:
    image: migrate/migrate:v4.18.3
    depends_on:
      postgres:
        condition: service_healthy
    command: |
      -path=/migrations/ -database "postgres://postgres:postgres@postgres:5432/support-portal?sslmode=disable" up
    restart: "no"
    volumes:
      - ./migrations:/migrations
    networks:
      - app-network

  support-portal:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "support-portal"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge